### ISSUE TITLE
Ambiguous use of operator '=='

### ISSUE THREAD

**Issue by VeinGuo** [vitoziv/VideoCat#1]
TimeLineView.swift  649行   判断
if currentItem.duration == kCMTimeZero { return }

if CMTimeCompare(currentItem.duration, kCMTimeZero) == 0 { return }

![image](https://user-images.githubusercontent.com/14232017/45551576-f5805680-b860-11e8-89bc-a90cd5eff01f.png)

**Comment by vitoziv** [comment]
fixed c4dec749b3cde7f3b6dbc26696eb00739e4beefd
